Repository projectcalico/calicoctl, pull requests merged in 2019-04, with the labels that each got.

#1988 Update libcalico to include VXLAN changes
  glide.lock
  glide.yaml
  test-data/v3/ippool.yaml
  tests/st/utils/data.py
Labels: docs-not-required, release-note-not-required

#1989 Add VXLANMODE to IP pools output.
  calicoctl/commands/convert.go
  calicoctl/commands/resources.go
  calicoctl/resourcemgr/ippool.go
  calicoctl/resourcemgr/resourcemgr.go
  tests/st/utils/data.py
Labels: docs-pr-required, release-note-not-required

#1991 [master] Automatic patch of libcalico-go to 43c1da882b70aba9d0325e7de4393439ef202550
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#1992 [master] Automatic update of libcalico-go to 43d572414857cc6f4d7242d9a23422cbc552f84a
  glide.lock
  glide.yaml
Labels: docs-not-reqiured, release-note-not-required

#1994 [release-v3.6] Automatic patch of libcalico-go to 24a5a971c54bf0f43417bbfccd0b31e7ffa19a98
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#1995 [release-v3.5] Automatic patch of libcalico-go to aae6c757ef3745eb6ecb45351470e66c54fd9e13
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#1997 [release-v3.7] Automatic patch of libcalico-go to 6860ff2cfd923a870ff7a76563ce825d6e47adb8
  glide.lock
  glide.yaml
  tests/st/calicoctl/test_crud.py
Labels: docs-not-required, release-note-not-required
