Repository projectcalico/calicoctl, pull requests merged in 2019-05, with the labels that each got.

#1998 Allow delete/get to specify multiple names
  calicoctl/commands/argutils/args.go
  calicoctl/commands/delete.go
  calicoctl/commands/get.go
  calicoctl/commands/resources.go
  calicoctl/resourcemgr/resourcemgr.go
  tests/st/calicoctl/test_crud.py
  tests/st/utils/data.py
  tests/st/utils/utils.py
Labels: docs-pr-required, release-note-required

#2001 fixed typo in get.go docs
  calicoctl/commands/get.go
Labels: docs-not-required, release-note-not-required

#2000 All error messages go to stderr
  calicoctl/calicoctl.go
  calicoctl/commands/apply.go
  calicoctl/commands/convert.go
  calicoctl/commands/create.go
  calicoctl/commands/delete.go
  calicoctl/commands/get.go
  calicoctl/commands/ipam.go
  calicoctl/commands/ipam/release.go
  calicoctl/commands/ipam/show.go
  calicoctl/commands/label.go
  calicoctl/commands/node/checksystem.go
  calicoctl/commands/node/diags.go
  calicoctl/commands/node/run.go
  calicoctl/commands/node/status.go
  calicoctl/commands/node_darwin.go
  calicoctl/commands/node_linux.go
  calicoctl/commands/node_windows.go
  calicoctl/commands/replace.go
  calicoctl/commands/resources.go
  calicoctl/commands/version.go
Labels: docs-not-required, release-note-not-required

#2004 Fix regression in reporting errors in ipam show
  calicoctl/commands/ipam/show.go
Labels: docs-not-required, release-note-not-required

#2003 Fixed missing new line in get errors
  calicoctl/commands/get.go
Labels: docs-not-required, release-note-not-required

#2002 Always rebuild when DEV_BUILD=true
  Makefile
Labels: docs-not-required, release-note-not-required

#2005 Update of libcalico-go
  glide.lock
  glide.yaml
  tests/st/calicoctl/test_crud.py
Labels: docs-not-required, release-note-not-required

#2007 Add install section for README
  README.md
Labels: docs-not-required, release-note-not-required

#2012 Fix "Unknown" ASN being shown.
  calicoctl/commands/printer.go
Labels: docs-pr-required, release-note-required

#2014 Fix "Unknown" ASN being shown & error type check
  calicoctl/commands/printer.go
Labels: docs-pr-required, release-note-not-required, release-note-required

#2011 IPAM utilization reporting
  Makefile
  calicoctl/commands/ipam.go
  calicoctl/commands/ipam/show.go
  tests/fv/ipam_test.go
  tests/fv/utils/calicoctl.go
Labels: docs-pr-required, hold-merge, release-note-required

#2017 Fix showing IPS IN USE from a large pool as 0
  calicoctl/commands/ipam/show.go
  tests/fv/ipam_test.go
Labels: docs-pr-required, release-note-not-required

#2015 Remove unmarshalling when creating a resource
  calicoctl/resourcemgr/resourcemgr.go
  calicoctl/resourcemgr/resourcemgr_test.go
  tests/st/calicoctl/test_crud.py
Labels: cherry-pick-candidate, docs-not-required, release-note-required
