Repository projectcalico/calicoctl, pull requests merged in 2019-06, with the labels that each got.

#2016 calicoctl node run: Plumb in $ETCD_DISCOVERY_SRV
  calicoctl/commands/node/run.go
Labels: docs-not-required, release-note-not-required

#2019 Improve output for IP attributes
  calicoctl/commands/ipam/show.go
  tests/fv/ipam_test.go
Labels: docs-not-required, release-note-not-required

#2020 Fix crash in ipam when NewClient fails
  calicoctl/commands/ipam/show.go
  tests/st/calicoctl/test_crud.py
  tests/st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#2023 [release-v3.7] Automatic patch of libcalico-go to 8898b03e9d624b38f903a530ffc40f8a39a433d9
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2024 Automated cherry pick of #2015: Remove validation when unmarshalling a resource
  calicoctl/resourcemgr/resourcemgr.go
  calicoctl/resourcemgr/resourcemgr_test.go
  tests/st/calicoctl/test_crud.py
Labels: docs-not-required, release-note-required

#2026 Rev libcalico-go to 487ec57127d266ef742a9e2553f720c51a2e8928
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#2025 Rev libcalico-go to pick up felix config name change.
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#2022 Output empty string instead of map[] if attribute doesn't exist
  calicoctl/commands/printer.go
  calicoctl/commands/printer_test.go
Labels: docs-not-required, release-note-not-required
