Repository projectcalico/calicoctl, pull requests merged in 2019-11, with the labels that each got.

#2076 [release-v3.10] Automatic patch of libcalico-go to 8f81e1e344ce1dc436b066ea242e4da5df765a97
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2075 fix calicoctl replace --help Description error
  calicoctl/commands/replace.go
Labels: docs-pr-required, release-note-required

#2077 [release-v3.9] Automatic patch of libcalico-go to 1891db7ae73bcafe01c90943f5eaac25ec53c96d
  go.mod
  go.sum
  tests/st/utils/data.py
Labels: docs-not-required, release-note-not-required

#2078 Fixing EXTRA_DOCKER_ARGS
  Makefile
Labels: docs-pr-required, release-note-required

#2079 node diags: auto remove ipset list container
  calicoctl/commands/node/diags.go
Labels: docs-not-required, release-note-required

#2080 Remove incorrect REAMDE content
  README.md
Labels: docs-not-required, release-note-not-required

#2081 node diags: use shorthand for netstat
  calicoctl/commands/node/diags.go
Labels: docs-not-required, release-note-required

#2082 Clean up a few things from go.sum
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2084 Fix clean step in makefile
  Makefile
Labels: docs-not-required, release-note-not-required

#2085 Move common Makefile targets to Makefile.common
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2086 Switch Makefile.common from wget to curl, remove wget dependency
  Makefile
Labels: docs-not-required, release-note-not-required
