Repository projectcalico/calicoctl, pull requests merged in 2020-08, with the labels that each got.

#2157 Remove vendor dir if it exists on clean
  Makefile
Labels: docs-not-required, release-note-not-required

#2151 Update crds
  calicoctl/commands/crds/crds.go
Labels: docs-not-required, release-note-not-required

#2160 CRD import fixes
  Makefile
  calicoctl/commands/crds/crds.go
Labels: docs-not-required, release-note-not-required

#2161 Add ability to specify directory as filename parameter
  calicoctl/calicoctl.go
  calicoctl/commands/apply.go
  calicoctl/commands/common/resources.go
  calicoctl/commands/create.go
  calicoctl/commands/datastore.go
  calicoctl/commands/datastore/migrate.go
  calicoctl/commands/delete.go
  calicoctl/commands/file/file_suite_test.go
  calicoctl/commands/file/iter.go
  calicoctl/commands/file/iter_test.go
  calicoctl/commands/get.go
  calicoctl/commands/ipam/release.go
  calicoctl/commands/label.go
  calicoctl/commands/node/node_suite_test.go
  calicoctl/commands/node/run.go
  calicoctl/commands/node_linux.go
  calicoctl/commands/patch.go
  calicoctl/commands/replace.go
  calicoctl/commands/version.go
  calicoctl/resourcemgr/resourcemgr.go
  calicoctl/resourcemgr/resourcemgr_test.go
Labels: docs-pr-required, release-note-required

#2164 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2165 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2167 Fix the default value of the K8s client QPS
  calicoctl/commands/datastore/migrate/import.go
Labels: docs-not-required, release-note-required

#2166 Fix the default value of the K8s client QPS
  calicoctl/commands/datastore/migrate/import.go
Labels: docs-not-required, release-note-required
