Repository projectcalico/calicoctl, pull requests merged in 2020-12, with the labels that each got.

#2230 Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#2231 Automated cherry pick of #2230: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#2232 Automated cherry pick of #2230: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-pr-required, release-note-required

#2233 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2234 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2236 Automated cherry pick of #2235: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#2235 Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#2237 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2238 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2240 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
