Repository projectcalico/calicoctl, pull requests merged in 2020-04, with the labels that each got.

#2114 Operator: Update calicoctl to ubi as base image
  Dockerfile.amd64
  Makefile
Labels: docs-not-required, release-note-required

#2113 Update go-build to v0.37
  Makefile
Labels: docs-not-required, release-note-not-required

#2121 Update libcalico-go pin and update tests
  go.mod
  go.sum
  tests/st/calicoctl/test_crud.py
Labels: docs-not-required, release-note-not-required

#2119 ipam configure strictaffinity
  calicoctl/commands/ipam.go
  calicoctl/commands/ipam/configure.go
  calicoctl/commands/ipam/show.go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2122 Rename configuration option to show-configuration
  calicoctl/commands/ipam/show.go
Labels: docs-not-required, release-note-not-required

#2102 add comment for using ST_TO_RUN variable
  Makefile
Labels: docs-not-required, release-note-not-required

#2123 Rev libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2124 Remove un-necessary extra print.
  calicoctl/commands/ipam/show.go
Labels: docs-not-required, release-note-not-required
