Repository projectcalico/calicoctl, pull requests merged in 2020-10, with the labels that each got.

#2194 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2195 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2196 Migrate ipam nodename 3.16
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/migrateipam.go
Labels: docs-not-required, release-note-required

#2197 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2198 Migrate ipam nodename 3.15
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/migrateipam.go
Labels: docs-not-required, release-note-required

#2200 Cherry pick BGP password support from master
  go.mod
  go.sum
  tests/st/calicoctl/test_crud.py
Labels: docs-not-required, release-note-not-required

#2201 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2203 Update go-build version to v0.48 (go 1.15.2)
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2205 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2199 Add IPAM migration unit tests and node handling for BGP configurations
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/export_test.go
  calicoctl/commands/datastore/migrate/migrate_suite_test.go
  calicoctl/commands/datastore/migrate/migrateipam_test.go
  tests/st/calicoctl/test_migrate.py
  tests/st/utils/data.py
Labels: docs-not-required, release-note-not-required

#2206 Add handling for v1 validations and node names in BGP configurations
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/export_test.go
  calicoctl/commands/datastore/migrate/migrate_suite_test.go
  calicoctl/commands/datastore/migrate/migrateipam_test.go
  tests/st/calicoctl/test_migrate.py
  tests/st/utils/data.py
Labels: docs-not-required, release-note-required

#2207 Add handling for v1 validations and node names in BGP configurations
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/export_test.go
  calicoctl/commands/datastore/migrate/migrate_suite_test.go
  calicoctl/commands/datastore/migrate/migrateipam_test.go
  tests/st/calicoctl/test_migrate.py
  tests/st/utils/data.py
Labels: docs-not-required, release-note-required

#2209 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2210 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
