Repository projectcalico/calicoctl, pull requests merged in 2020-07, with the labels that each got.

#2152 Fix import from libcalico-go
  Makefile
Labels: docs-not-required, release-note-not-required

#2148 Fix CVEs, use scratch based Image
  Dockerfile.amd64
  Makefile
  calicoctl-wait/calicoctl-wait.go
Labels: docs-pr-required, release-note-required

#2153 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2154 pin-updates libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2155 Upgrade to Golang 1.14
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-required
