Repository projectcalico/calicoctl, pull requests merged in 2020-11, with the labels that each got.

#2214 [master] Automatic update of sempahore YAMLs.
  .semaphore/clear_cache.yml
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#2215 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2216 Fix release branch pin update regex (add ^ to start)
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#2218 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2217 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2219 Handle docstring binary name changes for kubectl plugin
  calicoctl/calicoctl.go
  calicoctl/commands/apply.go
  calicoctl/commands/convert.go
  calicoctl/commands/create.go
  calicoctl/commands/datastore.go
  calicoctl/commands/datastore/migrate.go
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/import.go
  calicoctl/commands/datastore/migrate/lock.go
  calicoctl/commands/datastore/migrate/unlock.go
  calicoctl/commands/delete.go
  calicoctl/commands/get.go
  calicoctl/commands/ipam.go
  calicoctl/commands/ipam/configure.go
  calicoctl/commands/ipam/release.go
  calicoctl/commands/ipam/show.go
  calicoctl/commands/label.go
  calicoctl/commands/node/checksystem.go
  calicoctl/commands/node/diags.go
  calicoctl/commands/node/run.go
  calicoctl/commands/node/status.go
  calicoctl/commands/node_linux.go
  calicoctl/commands/patch.go
  calicoctl/commands/replace.go
  calicoctl/commands/version.go
  calicoctl/util/docstring.go
  tests/st/calicoctl/test_flags.py
Labels: docs-not-required, release-note-not-required

#2220 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2222 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2224 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2223 comply with the go mod versioning constrains
  calicoctl/calicoctl.go
  calicoctl/commands/apply.go
  calicoctl/commands/clientmgr/client.go
  calicoctl/commands/common/printer.go
  calicoctl/commands/common/resources.go
  calicoctl/commands/convert.go
  calicoctl/commands/create.go
  calicoctl/commands/datastore.go
  calicoctl/commands/datastore/migrate.go
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/export_test.go
  calicoctl/commands/datastore/migrate/import.go
  calicoctl/commands/datastore/migrate/lock.go
  calicoctl/commands/datastore/migrate/migrateipam_test.go
  calicoctl/commands/datastore/migrate/unlock.go
  calicoctl/commands/delete.go
  calicoctl/commands/file/iter.go
  calicoctl/commands/file/iter_test.go
  calicoctl/commands/get.go
  calicoctl/commands/ipam.go
  calicoctl/commands/ipam/configure.go
  calicoctl/commands/ipam/release.go
  calicoctl/commands/ipam/show.go
  calicoctl/commands/label.go
  calicoctl/commands/node/checksystem.go
  calicoctl/commands/node/diags.go
  calicoctl/commands/node/run.go
  calicoctl/commands/node/status.go
  calicoctl/commands/node_linux.go
  calicoctl/commands/patch.go
  calicoctl/commands/replace.go
  calicoctl/commands/v1resourceloader/v1resourceloader.go
  calicoctl/commands/version.go
  calicoctl/resourcemgr/resourcemgr.go
  calicoctl/resourcemgr/resourcemgr_test.go
  go.mod
  tests/fv/ipam_test.go
  tests/fv/migrate_ipam_test.go
Labels: docs-pr-required, release-note-required

#2227 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2228 update pins
  Makefile
  calicoctl/commands/datastore/migrate/import.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2212 --context support to calicoctl
  calicoctl/calicoctl.go
  calicoctl/commands/apply.go
  calicoctl/commands/create.go
  calicoctl/commands/delete.go
  calicoctl/commands/get.go
  calicoctl/commands/label.go
  calicoctl/commands/patch.go
  calicoctl/commands/replace.go
  test-data/kubectl-config.yaml
  tests/fv/multi_context_test.go
  tests/fv/utils/calicoctl.go
Labels: docs-pr-required, release-note-required
