Repository projectcalico/calicoctl, pull requests merged in 2020-09, with the labels that each got.

#2170 Update pins - pick up FelixConfiguration
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2171 [release-v3.16] Update pins - pick up FelixConfiguration
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2172 [release-v3.15] Update pins - pick up FelixConfiguration
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2173 Add KubeControllersConfiguration to the datastore migration
  calicoctl/commands/datastore/migrate/export.go
Labels: docs-pr-required, release-note-required

#2175 Add KubeControllersConfiguration to the datastore migration
  calicoctl/commands/datastore/migrate/export.go
Labels: docs-pr-required, release-note-required

#2176 Add KubeControllersConfiguration to the datastore migration
  calicoctl/commands/datastore/migrate/export.go
Labels: docs-completed, release-note-required

#2162 Version poll
  Dockerfile.amd64
  Makefile
  calicoctl-wait/calicoctl-wait.go
  calicoctl/commands/version.go
Labels: docs-completed, release-note-not-required

#2177 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2179 Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2180 Rev libcalico-go to pick up defaulting fix.
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2184 Semaphore v2 migration / add pin update pipeline
  .semaphore/clear_cache.yml
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2188 Build image before CD
  Makefile
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#2189 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2191 Allow semaphore-run-auto-pin-update-workflows to set the SEMAPHORE_PROJECT_ID (only default it if it's not set)
  Makefile
Labels: docs-not-required, release-note-not-required

#2186 Fix datastore migration to properly assign Kubernetes nodenames in the migrated IPAM data
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/migrateipam.go
Labels: docs-not-required, release-note-required

#2193 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
