Repository projectcalico/calicoctl, pull requests merged in 2021-06, with the labels that each got.

#2336 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2337 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#2338 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2339 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#2341 Replace lib/v3 package with projectcalico/api
  calicoctl/commands/argutils/validate.go
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/export_test.go
  calicoctl/commands/datastore/migrate/import.go
  calicoctl/commands/version.go
  calicoctl/resourcemgr/bgpconfig.go
  calicoctl/resourcemgr/bgppeer.go
  calicoctl/resourcemgr/clusterinfo.go
  calicoctl/resourcemgr/felixconfig.go
  calicoctl/resourcemgr/globalnetworkpolicy.go
  calicoctl/resourcemgr/globalnetworkset.go
  calicoctl/resourcemgr/hostendpoint.go
  calicoctl/resourcemgr/ippool.go
  calicoctl/resourcemgr/kubecontrollersconfig.go
  calicoctl/resourcemgr/kubecontrollersconfig_test.go
  calicoctl/resourcemgr/networkpolicy.go
  calicoctl/resourcemgr/networkset.go
  calicoctl/resourcemgr/profile.go
  calicoctl/resourcemgr/resourcemgr.go
  calicoctl/resourcemgr/resourcemgr_test.go
  go.mod
  go.sum
  tests/fv/ipam_test.go
  tests/fv/migrate_ipam_test.go
  tests/fv/namespace_option_test.go
Labels: docs-pr-required, release-note-required

#2342 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2343 Update api pins on pin update
  Makefile
Labels: docs-not-required, release-note-not-required

#2345 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2346 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2347 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
