Repository projectcalico/calicoctl, pull requests merged in 2021-02, with the labels that each got.

#2252 Fix version reporting
  Makefile
Labels: docs-pr-required, release-note-required

#2254 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2256 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2253 Add tests for projectcalico/libcalico-go#1361
  Makefile
  test-data/kubectl-config-second.yaml
  tests/fv/multi_context_test.go
  tests/st/manifests/mock-node-second.yaml
Labels: docs-not-required, release-note-not-required

#2247 Additional IPAM sub commands
  calicoctl/commands/clientmgr/client.go
  calicoctl/commands/crds/decode.go
  calicoctl/commands/ipam.go
  calicoctl/commands/ipam/check.go
  calicoctl/commands/ipam/release.go
  calicoctl/commands/node/checksystem.go
  calicoctl/commands/node/diags.go
  calicoctl/commands/node/status.go
  go.mod
  tests/fv/multi_context_test.go
Labels: docs-pr-required, release-note-required

#2257 Fix docstring for check command
  calicoctl/commands/ipam/check.go
Labels: docs-completed, release-note-not-required

#2258 Add help text for show-all-ips and show-problem-ips
  calicoctl/commands/ipam/check.go
Labels: docs-pr-required, release-note-not-required

#2260 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2264 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2265 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2266 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
