Repository projectcalico/calicoctl, pull requests merged in 2021-01, with the labels that each got.

#2245 [master] Semaphore Auto Pin Update
  calicoctl/calicoctl.go
  calicoctl/commands/apply.go
  calicoctl/commands/convert.go
  calicoctl/commands/create.go
  calicoctl/commands/datastore.go
  calicoctl/commands/datastore/migrate.go
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/import.go
  calicoctl/commands/datastore/migrate/lock.go
  calicoctl/commands/datastore/migrate/unlock.go
  calicoctl/commands/delete.go
  calicoctl/commands/get.go
  calicoctl/commands/ipam.go
  calicoctl/commands/ipam/configure.go
  calicoctl/commands/ipam/release.go
  calicoctl/commands/ipam/show.go
  calicoctl/commands/label.go
  calicoctl/commands/node/checksystem.go
  calicoctl/commands/node/diags.go
  calicoctl/commands/node/run.go
  calicoctl/commands/node/status.go
  calicoctl/commands/node_linux.go
  calicoctl/commands/patch.go
  calicoctl/commands/replace.go
  calicoctl/commands/version.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2246 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2243 calicoctl get -A option support
  calicoctl/commands/get.go
  tests/fv/namespace_option_test.go
Labels: docs-pr-required, release-note-required

#2248 Handle namespaced resources during datastore migration properly
  Makefile
  calicoctl/commands/datastore/migrate/export.go
  tests/st/calicoctl/test_migrate.py
  tests/st/utils/data.py
  tests/st/utils/utils.py
Labels: docs-not-required, release-note-required

#2251 Handle namespaced resources during datastore migration properly
  Makefile
  calicoctl/commands/datastore/migrate/export.go
  tests/st/calicoctl/test_migrate.py
  tests/st/utils/data.py
  tests/st/utils/utils.py
Labels: docs-not-required, release-note-required

#2250 Handle namespaced resources during datastore migration properly
  Makefile
  calicoctl/commands/datastore/migrate/export.go
  tests/st/calicoctl/test_migrate.py
  tests/st/utils/data.py
  tests/st/utils/utils.py
Labels: docs-not-required, release-note-required

#2249 Handle namespaced resources during datastore migration properly
  Makefile
  calicoctl/commands/datastore/migrate/export.go
  tests/st/calicoctl/test_migrate.py
  tests/st/utils/data.py
  tests/st/utils/utils.py
Labels: docs-not-required, release-note-required
