Repository projectcalico/calicoctl, pull requests merged in 2021-08, with the labels that each got.

#2392 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2390 Refactor version mismatch checking to not need argument parsing
  Makefile
  calicoctl/calicoctl.go
  calicoctl/commands/apply.go
  calicoctl/commands/common/resources.go
  calicoctl/commands/common/version_mismatch.go
  calicoctl/commands/convert.go
  calicoctl/commands/create.go
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/import.go
  calicoctl/commands/datastore/migrate/lock.go
  calicoctl/commands/datastore/migrate/unlock.go
  calicoctl/commands/delete.go
  calicoctl/commands/get.go
  calicoctl/commands/ipam/check.go
  calicoctl/commands/ipam/configure.go
  calicoctl/commands/ipam/release.go
  calicoctl/commands/ipam/show.go
  calicoctl/commands/label.go
  calicoctl/commands/node/checksystem.go
  calicoctl/commands/node/diags.go
  calicoctl/commands/node/run.go
  calicoctl/commands/node/status.go
  calicoctl/commands/patch.go
  calicoctl/commands/replace.go
  calicoctl/commands/version.go
  tests/st/calicoctl/test_flags.py
Labels: release-note-required, docs-pr-required

#2393 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2395 Change release repo to docker.io, add RELEASE and CONFIRM env variables
  Makefile
Labels: docs-not-required, release-note-not-required

#2396 Automated cherry pick of #2395: Change release repo to docker.io, add RELEASE and CONFIRM env
  Makefile
Labels: docs-not-required, release-note-not-required

#2397 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2399 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2400 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2401 fix the cd target
  Makefile
Labels: docs-not-required, release-note-not-required

#2402 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2403 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2405 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
