Repository projectcalico/calicoctl, pull requests merged in 2021-09, with the labels that each got.

#2394 Updating apk-tools in Alpine-based images
  Dockerfile.arm64
  Dockerfile.armv7
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: release-note-required, docs-not-required, merge-when-ready

#2406 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2407 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2408 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2409 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2411 [master] Semaphore Auto Pin Update
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2412 ARM64 dockerfile updates
  Dockerfile.arm64
  Makefile
Labels: docs-not-required, release-note-not-required

#2414 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2418 Only build amd64 images for now
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#2419 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2421 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2426 Automated cherry pick of #2390: Refactor version mismatch checking to not need argument
  Makefile
  calicoctl/calicoctl.go
  calicoctl/commands/apply.go
  calicoctl/commands/common/resources.go
  calicoctl/commands/common/version_mismatch.go
  calicoctl/commands/convert.go
  calicoctl/commands/create.go
  calicoctl/commands/datastore/migrate/export.go
  calicoctl/commands/datastore/migrate/import.go
  calicoctl/commands/datastore/migrate/lock.go
  calicoctl/commands/datastore/migrate/unlock.go
  calicoctl/commands/delete.go
  calicoctl/commands/get.go
  calicoctl/commands/ipam/check.go
  calicoctl/commands/ipam/configure.go
  calicoctl/commands/ipam/release.go
  calicoctl/commands/ipam/show.go
  calicoctl/commands/label.go
  calicoctl/commands/node/checksystem.go
  calicoctl/commands/node/diags.go
  calicoctl/commands/node/run.go
  calicoctl/commands/node/status.go
  calicoctl/commands/patch.go
  calicoctl/commands/replace.go
  calicoctl/commands/version.go
  tests/st/calicoctl/test_flags.py
Labels: docs-not-required, release-note-not-required

#2424 Fix version mismatch error message formatting
  calicoctl/commands/common/version_mismatch.go
Labels: docs-not-required, release-note-not-required
