Repository projectcalico/calicoctl, pull requests merged in 2021-11, with the labels that each got.

#2447 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2448 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2449 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2450 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2451 [release-v3.21] Auto pick #2446: Add disableBGPExport support to IP Pools wide output
  calicoctl/resourcemgr/ippool.go
  tests/st/utils/data.py
Labels: docs-not-required, release-note-not-required

#2415 Multiarch image adjustments
  Dockerfile.arm64
  Dockerfile.armv7
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
Labels: release-note-required, docs-pr-required

#2452 Automated cherry pick of #2415: Multiarchitectural support
  Dockerfile.arm64
  Dockerfile.armv7
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
Labels: docs-not-required, release-note-not-required

#2453 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2454 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2455 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2456 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2457 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2459 Remove TTY flag from docker exec
  Makefile
Labels: docs-not-required, release-note-not-required

#2458 Remove TTY flag from docker exec
  Makefile
Labels: release-note-required, docs-pr-required
