Repository projectcalico/calicoctl, pull requests merged in 2021-07, with the labels that each got.

#2348 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2350 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2351 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2352 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2354 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2355 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2358 Fix tests for a pin update
  go.mod
  go.sum
  tests/fv/ipam_test.go
  tests/fv/migrate_ipam_test.go
Labels: docs-not-required, release-note-not-required

#2359 Fix tests for a pin update
  go.mod
  go.sum
  tests/fv/ipam_test.go
  tests/fv/migrate_ipam_test.go
Labels: docs-not-required, release-note-not-required

#2360 Fix pins for v3.20
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2361 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2362 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2363 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2364 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2365 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2353 Add client/cluster version mismatch verification
  Makefile
  calicoctl/calicoctl.go
  calicoctl/commands/version.go
  tests/fv/helper/calico_version_helper.go
  tests/fv/ipam_test.go
  tests/fv/migrate_ipam_test.go
  tests/fv/multi_context_test.go
  tests/fv/namespace_option_test.go
  tests/fv/utils/calicoctl.go
  tests/st/calicoctl/test_flags.py
  tests/st/manifests/crd.projectcalico.org_clusterinformations.yaml
  tests/st/utils/utils.py
Labels: docs-pr-required, release-note-required

#2366 Add client/cluster version mismatch verification
  Makefile
  calicoctl/calicoctl.go
  calicoctl/commands/version.go
  tests/fv/helper/calico_version_helper.go
  tests/fv/ipam_test.go
  tests/fv/migrate_ipam_test.go
  tests/fv/multi_context_test.go
  tests/fv/namespace_option_test.go
  tests/fv/utils/calicoctl.go
  tests/st/calicoctl/test_flags.py
  tests/st/manifests/crd.projectcalico.org_clusterinformations.yaml
  tests/st/utils/utils.py
Labels: docs-not-required, release-note-not-required

#2367 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2369 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2370 Skip version mismatch check when ClusterInformation does not exist
  calicoctl/commands/version.go
Labels: docs-not-required, release-note-not-required

#2371 Skip version mismatch check when CalicoVersion not specified in cluster
  calicoctl/commands/version.go
  tests/st/calicoctl/test_flags.py
Labels: docs-not-required, release-note-not-required

#2368 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2372 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2373 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2374 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2375 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2376 Update release targets
  Makefile
Labels: docs-not-required, release-note-not-required

#2378 Automated cherry pick of #2370: Skip version mismatch check when ClusterInformation does
  calicoctl/commands/version.go
Labels: docs-not-required, release-note-not-required

#2379 Automated cherry pick of #2371: Skip version mismatch check when CalicoVersion not
  calicoctl/commands/version.go
  tests/st/calicoctl/test_flags.py
Labels: docs-not-required, release-note-not-required

#2377 Update release targets
  Makefile
Labels: docs-not-required, release-note-not-required

#2380 Add license to calico_version_helper.go
  tests/fv/helper/calico_version_helper.go
Labels: docs-not-required, release-note-not-required

#2381 Add license to calico_version_helper.go
  tests/fv/helper/calico_version_helper.go
Labels: docs-not-required, release-note-not-required

#2382 Revert error message
  calicoctl/calicoctl.go
  tests/st/calicoctl/test_flags.py
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2383 Revert error message
  calicoctl/calicoctl.go
  tests/st/calicoctl/test_flags.py
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2385 Fix release target
  Makefile
Labels: docs-pr-required, release-note-required

#2386 Automated cherry pick of #2385: Fix release target
  Makefile
Labels: docs-not-required, release-note-not-required

#2387 Skip version mismatch check for commands with no API access required
  calicoctl/commands/version.go
  tests/fv/multi_context_test.go
Labels: docs-not-required, release-note-not-required

#2389 Automated cherry pick of #2387: Skip version mismatch check for commands with no API
  calicoctl/commands/version.go
  tests/fv/multi_context_test.go
Labels: docs-pr-required, release-note-required
